/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package front.vista.simulacion;

import objects.Calculator;
import objects.Controller;

/**
 *
 * @author nicolashefty
 */
public class SimulacionMontecarlo extends javax.swing.JFrame {

    Controller controller;
    Calculator calculator = new Calculator();

    /**
     * Creates new form SimulacionMontecarlo
     */
    public SimulacionMontecarlo(int cant, int desde, int hasta, Controller cont) {
        controller = cont;
        initComponents();
        calculator.tablas(this, cant, desde, hasta);
        setLocationRelativeTo(null);
        resultado_txt.setText(Double.toString((double)calculator.cantidadExperimentosValidos()/(double)cant));
    }

    public SimulacionMontecarlo(int cant, int desde, int hasta, Controller cont, int cantRondas, int puntosPrimerTiro, int puntosSegundoTiro, int valorASuperar) {
        controller = cont;
        initComponents();
        calculator.tablas(this, cant, desde, hasta, cantRondas, puntosPrimerTiro, puntosSegundoTiro, valorASuperar);
        setLocationRelativeTo(null);
        resultado_txt.setText(Double.toString((double)calculator.cantidadExperimentosValidos()/(double)cant));
        calculator.volver();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simulationTable = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        _scpPrimerTiro = new javax.swing.JScrollPane();
        tblPrimerTiro = new javax.swing.JTable();
        _scpSegundoTiro7 = new javax.swing.JScrollPane();
        tblDespues7 = new javax.swing.JTable();
        _scpSegundoTiro8 = new javax.swing.JScrollPane();
        tblDespues8 = new javax.swing.JTable();
        _scpSegundoTiro9 = new javax.swing.JScrollPane();
        tblDespues9 = new javax.swing.JTable();
        _lblDespues8 = new javax.swing.JLabel();
        _lblPrimerTiro = new javax.swing.JLabel();
        _lbl7antes = new javax.swing.JLabel();
        lblDespues9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        _scpMontecarlo = new javax.swing.JScrollPane();
        _tblMontecarlo = new javax.swing.JTable();
        _lblTituloMontecarlo = new javax.swing.JLabel();
        _pnlResultadosMontecarlo = new javax.swing.JPanel();
        resultado_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vector Estado");

        tblPrimerTiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(7),  new Float(0.12),  new Float(0.12),  new Integer(0),  new Integer(11)},
                { new Integer(8),  new Float(0.15),  new Float(0.27),  new Integer(12),  new Integer(26)},
                { new Integer(9),  new Float(0.18),  new Float(0.45),  new Integer(27),  new Integer(44)},
                { new Integer(10),  new Float(0.55),  new Float(1.0),  new Integer(45),  new Integer(99)}
            },
            new String [] {
                "# Pinos", "Probabilidad", "P. Acumulada", "Desde", "Hasta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPrimerTiro.getTableHeader().setReorderingAllowed(false);
        _scpPrimerTiro.setViewportView(tblPrimerTiro);

        tblDespues7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(0),  new Float(0.02),  new Float(0.02),  new Integer(0),  new Integer(1)},
                { new Integer(1),  new Float(0.1),  new Float(0.12),  new Integer(2),  new Integer(11)},
                { new Integer(2),  new Float(0.45),  new Float(0.57),  new Integer(12),  new Integer(56)},
                { new Integer(3),  new Float(0.43),  new Float(1.0),  new Integer(57),  new Integer(99)}
            },
            new String [] {
                "# Pinos", "Probabilidad", "P. Acumulada", "Desde", "Hasta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDespues7.getTableHeader().setReorderingAllowed(false);
        _scpSegundoTiro7.setViewportView(tblDespues7);

        tblDespues8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(0),  new Float(0.04),  new Float(0.04),  new Integer(0),  new Integer(3)},
                { new Integer(1),  new Float(0.2),  new Float(0.24),  new Integer(4),  new Integer(23)},
                { new Integer(2),  new Float(0.76),  new Float(1.0),  new Integer(24),  new Integer(99)}
            },
            new String [] {
                "# Pinos", "Probabilidad", "P. Acumulada", "Desde", "Hasta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDespues8.getTableHeader().setReorderingAllowed(false);
        _scpSegundoTiro8.setViewportView(tblDespues8);

        tblDespues9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(0),  new Float(0.06),  new Float(0.06),  new Integer(0),  new Integer(5)},
                { new Integer(1),  new Float(0.94),  new Float(1.0),  new Integer(6),  new Integer(99)}
            },
            new String [] {
                "# Pinos", "Probabilidad", "P. Acumulada", "Desde", "Hasta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDespues9.getTableHeader().setReorderingAllowed(false);
        _scpSegundoTiro9.setViewportView(tblDespues9);

        _lblDespues8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        _lblDespues8.setForeground(new java.awt.Color(102, 102, 102));
        _lblDespues8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _lblDespues8.setText("Distribución - Cantidad de pinos tirados en el segundo tiro si se tiraron 8 antes");

        _lblPrimerTiro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        _lblPrimerTiro.setForeground(new java.awt.Color(102, 102, 102));
        _lblPrimerTiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _lblPrimerTiro.setText("Distribución - Cantidad de pinos tirados en el primer tiro");

        _lbl7antes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        _lbl7antes.setForeground(new java.awt.Color(102, 102, 102));
        _lbl7antes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _lbl7antes.setText("Distribución - Cantidad de pinos tirados en el segundo tiro si se tiraron 7 antes");

        lblDespues9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDespues9.setForeground(new java.awt.Color(102, 102, 102));
        lblDespues9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDespues9.setText("Distribución - Cantidad de pinos tirados en el segundo tiro si se tiraron 9 antes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_lblDespues8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_lblPrimerTiro)
                    .addComponent(_scpSegundoTiro8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(_scpPrimerTiro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(_scpSegundoTiro7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(90, 90, 90))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(_lbl7antes)
                            .addGap(80, 80, 80)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblDespues9))
                            .addComponent(_scpSegundoTiro9, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_lblPrimerTiro)
                    .addComponent(_lbl7antes))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_scpSegundoTiro7, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(_scpPrimerTiro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_lblDespues8)
                    .addComponent(lblDespues9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_scpSegundoTiro8, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(_scpSegundoTiro9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        simulationTable.addTab("Distribuciones de Frecuencias", jPanel1);

        _tblMontecarlo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "# Simulación", "# Ronda", "RND1", "1° Tiro", "RND2", "2° Tiro", "Total Pinos", "Puntos totales", "Puntos acumulados", "Supera 120 (S|N)", "Acumulador Supera 120"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        _tblMontecarlo.getTableHeader().setReorderingAllowed(false);
        _scpMontecarlo.setViewportView(_tblMontecarlo);
        if (_tblMontecarlo.getColumnModel().getColumnCount() > 0) {
            _tblMontecarlo.getColumnModel().getColumn(0).setResizable(false);
            _tblMontecarlo.getColumnModel().getColumn(0).setPreferredWidth(60);
            _tblMontecarlo.getColumnModel().getColumn(1).setResizable(false);
            _tblMontecarlo.getColumnModel().getColumn(1).setPreferredWidth(60);
            _tblMontecarlo.getColumnModel().getColumn(2).setResizable(false);
            _tblMontecarlo.getColumnModel().getColumn(2).setPreferredWidth(35);
            _tblMontecarlo.getColumnModel().getColumn(3).setResizable(false);
            _tblMontecarlo.getColumnModel().getColumn(3).setPreferredWidth(50);
            _tblMontecarlo.getColumnModel().getColumn(4).setResizable(false);
            _tblMontecarlo.getColumnModel().getColumn(4).setPreferredWidth(35);
            _tblMontecarlo.getColumnModel().getColumn(5).setResizable(false);
            _tblMontecarlo.getColumnModel().getColumn(5).setPreferredWidth(50);
            _tblMontecarlo.getColumnModel().getColumn(6).setResizable(false);
            _tblMontecarlo.getColumnModel().getColumn(6).setPreferredWidth(50);
            _tblMontecarlo.getColumnModel().getColumn(7).setResizable(false);
            _tblMontecarlo.getColumnModel().getColumn(7).setPreferredWidth(50);
            _tblMontecarlo.getColumnModel().getColumn(8).setResizable(false);
            _tblMontecarlo.getColumnModel().getColumn(9).setResizable(false);
            _tblMontecarlo.getColumnModel().getColumn(10).setResizable(false);
            _tblMontecarlo.getColumnModel().getColumn(10).setPreferredWidth(80);
        }
        _tblMontecarlo.getAccessibleContext().setAccessibleName("");
        _tblMontecarlo.getAccessibleContext().setAccessibleDescription("");

        _lblTituloMontecarlo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        _lblTituloMontecarlo.setForeground(new java.awt.Color(102, 102, 102));
        _lblTituloMontecarlo.setText("Vector Estado - Montecarlo");

        resultado_txt.setText("jTextField1");

        jLabel2.setText("La probabilidad de que supere es:");

        javax.swing.GroupLayout _pnlResultadosMontecarloLayout = new javax.swing.GroupLayout(_pnlResultadosMontecarlo);
        _pnlResultadosMontecarlo.setLayout(_pnlResultadosMontecarloLayout);
        _pnlResultadosMontecarloLayout.setHorizontalGroup(
            _pnlResultadosMontecarloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_pnlResultadosMontecarloLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(resultado_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(_pnlResultadosMontecarloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );
        _pnlResultadosMontecarloLayout.setVerticalGroup(
            _pnlResultadosMontecarloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_pnlResultadosMontecarloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultado_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Resultados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(_lblTituloMontecarlo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(91, 91, 91))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(_scpMontecarlo, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(_pnlResultadosMontecarlo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_lblTituloMontecarlo)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_pnlResultadosMontecarlo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_scpMontecarlo, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );

        simulationTable.addTab("Simulacion", jPanel2);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(simulationTable, javax.swing.GroupLayout.PREFERRED_SIZE, 1193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(simulationTable, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        controller.showDefault();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _lbl7antes;
    private javax.swing.JLabel _lblDespues8;
    private javax.swing.JLabel _lblPrimerTiro;
    private javax.swing.JLabel _lblTituloMontecarlo;
    private javax.swing.JPanel _pnlResultadosMontecarlo;
    private javax.swing.JScrollPane _scpMontecarlo;
    private javax.swing.JScrollPane _scpPrimerTiro;
    private javax.swing.JScrollPane _scpSegundoTiro7;
    private javax.swing.JScrollPane _scpSegundoTiro8;
    private javax.swing.JScrollPane _scpSegundoTiro9;
    public javax.swing.JTable _tblMontecarlo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDespues9;
    private javax.swing.JTextField resultado_txt;
    private javax.swing.JTabbedPane simulationTable;
    public javax.swing.JTable tblDespues7;
    public javax.swing.JTable tblDespues8;
    public javax.swing.JTable tblDespues9;
    public javax.swing.JTable tblPrimerTiro;
    // End of variables declaration//GEN-END:variables
}
